# Generated by Django 4.2.5 on 2023-09-14 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0003_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
