# Generated by Django 4.2.5 on 2023-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0004_alter_medicalhistory_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosis_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='previous_illnesses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgeries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
