# Generated by Django 4.2.5 on 2023-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0005_alter_appointment_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_doctor',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
