# Generated by Django 4.2.5 on 2023-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0006_appointment_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_with', models.CharField(max_length=10)),
            ],
        ),
    ]
