# Generated by Django 4.2.5 on 2023-09-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0007_appointmentwith'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentWith',
        ),
    ]
