# Generated by Django 4.2.5 on 2023-09-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_patient_info', 'Can view patient info'), ('add_edit_patient_info', 'Can edit patient info'), ('view_edit_appointment', 'Can edit patient appointment'), ('view_patient_med_history', 'Can view patient medical history'), ('edit_patient_med_history', 'Can edit patient medical history')),
            },
        ),
    ]
