# Generated by Django 4.2.5 on 2023-09-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
